export const SET_USERNAME = 'SET_USERNAME';
export const ADD_SERVER = 'ADD_SERVER';
export const DELETE_SERVER = 'DELETE_SERVER';
export const ADD_WEBSOCKET_CONNECTION = 'ADD_WEBSOCKET_CONNECTION';
export const DELETE_WEBSOCKET_CONNECTION = 'DELETE_WEBSOCKET_CONNECTION';
export const UPDATE_SERVER_STATUS = 'UPDATE_SERVER_STATUS';

export const FILES_FOR_SERVER_FETCHED = 'FILES_FOR_SERVER_FETCHED';
export const NEW_FILE_FOR_SERVER = 'NEW_FILE_FOR_SERVER';
export const DELETE_FILE_FOR_SERVER = 'DELETE_FILE_FOR_SERVER';

export const RECORDS_FOR_FILE_FETCHED = 'RECORDS_FOR_FILE_FETCHED';
export const NEW_RECORD_FOR_FILE = 'NEW_RECORD_FOR_FILE';
export const RECORD_FOR_FILE_REMOVED = 'RECORD_FOR_FILE_REMOVED';