export const SET_USERNAME = 'SET_USERNAME';
export const ADD_SERVER = 'ADD_SERVER';
export const DELETE_SERVER = 'DELETE_SERVER';
export const ADD_WEBSOCKET_CONNECTION = 'ADD_WEBSOCKET_CONNECTION';
export const DELETE_WEBSOCKET_CONNECTION = 'DELETE_WEBSOCKET_CONNECTION';
export const UPDATE_SERVER_STATUS = 'UPDATE_SERVER_STATUS';

export const FILES_FOR_SERVER_FETCHED = 'FILES_FOR_SERVER_FETCHED';
export const NEW_FILE_FOR_SERVER = 'NEW_FILE_FOR_SERVER';
export const DELETE_FILE_FOR_SERVER = 'DELETE_FILE_FOR_SERVER';